[CmdletBinding()]
param(
    [string] $InteropFile  = (Join-Path $PSScriptRoot '..\Strand7Sharp\Interop\St7API.cs'),
    [string] $OutputFile   = (Join-Path $PSScriptRoot '..\Strand7Sharp\Generated\St7ErrorCode.g.cs')
)
$ErrorActionPreference = 'Stop'
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputFile) | Out-Null

$src = [System.IO.File]::ReadAllText($InteropFile, [System.Text.UTF8Encoding]::new($false))

# Match `public const int (ERR7_Name|SE_Name) = <int>;`
$rx = [regex]'public\s+const\s+int\s+(ERR7|SE)_(?<name>[A-Za-z0-9_]+)\s*=\s*(?<val>-?\d+)\s*;'

# Collect (name, value) rows, de-duplicated on name (last wins if a name repeats in the source).
$byName = New-Object System.Collections.Specialized.OrderedDictionary
foreach ($m in $rx.Matches($src))
{
    $prefix = $m.Groups[1].Value
    $rawName = $m.Groups['name'].Value
    $val = [int]$m.Groups['val'].Value
    # Prefix SE_ entries with "Solver" so they can't collide with ERR7 names that
    # happen to share a base word.
    $enumName = if ($prefix -eq 'SE') { "Solver$rawName" } else { $rawName }
    if ($byName.Contains($enumName)) { $byName.Remove($enumName) }
    $byName[$enumName] = $val
}

# Group by value so we can emit primary names + aliases without picking up
# ordering-dependent duplicates.
$primaryByValue = @{}
$aliasesByValue = @{}
foreach ($key in $byName.Keys) {
    $v = [int]$byName[$key]
    if ($primaryByValue.ContainsKey($v)) {
        if (-not $aliasesByValue.ContainsKey($v)) { $aliasesByValue[$v] = New-Object System.Collections.Generic.List[string] }
        $aliasesByValue[$v].Add($key)
    } else {
        $primaryByValue[$v] = $key
    }
}

# Emit LF newlines regardless of host OS so the file matches the .gitattributes rule.
$NL = "`n"
$sb = New-Object System.Text.StringBuilder
[void]$sb.Append('// <auto-generated>' + $NL)
[void]$sb.Append('//     This file was generated by tools/Generate-ErrorCodes.ps1 from St7API.cs.' + $NL)
[void]$sb.Append('//     DO NOT EDIT BY HAND. Re-run the generator to refresh.' + $NL)
[void]$sb.Append('// </auto-generated>' + $NL)
[void]$sb.Append('#nullable enable' + $NL)
[void]$sb.Append($NL)
[void]$sb.Append('namespace Strand7Sharp;' + $NL)
[void]$sb.Append($NL)
[void]$sb.Append('/// <summary>' + $NL)
[void]$sb.Append('/// Symbolic names for every Strand7 error code exposed by <c>St7API.dll</c>.' + $NL)
[void]$sb.Append('/// Merges the API-error space (<c>ERR7_*</c>, range -12..468) with the disjoint' + $NL)
[void]$sb.Append('/// solver-error space (<c>SE_*</c>, 1001+) under a single enum. Solver entries' + $NL)
[void]$sb.Append('/// keep a <c>Solver</c> prefix so their names can never collide with API names.' + $NL)
[void]$sb.Append('/// </summary>' + $NL)
[void]$sb.Append('/// <remarks>' + $NL)
[void]$sb.Append('/// Values not listed here are still valid — cast any <c>int</c> to' + $NL)
[void]$sb.Append('/// <see cref="St7ErrorCode"/> to inspect. <see cref="None"/> is 0 (success).' + $NL)
[void]$sb.Append('/// </remarks>' + $NL)
[void]$sb.Append('public enum St7ErrorCode' + $NL)
[void]$sb.Append('{' + $NL)
[void]$sb.Append('    /// <summary>No error (successful call).</summary>' + $NL)
[void]$sb.Append('    None = 0,' + $NL)
[void]$sb.Append($NL)

$sortedValues = $primaryByValue.Keys | Sort-Object
foreach ($v in $sortedValues) {
    if ($v -eq 0) { continue }  # 'None' already emitted
    $name = $primaryByValue[$v]
    [void]$sb.Append("    $name = $v,$NL")
    if ($aliasesByValue.ContainsKey($v)) {
        foreach ($alias in $aliasesByValue[$v]) {
            [void]$sb.Append("    $alias = $v,$NL")
        }
    }
}

[void]$sb.Append('}' + $NL)

# Write UTF-8 (no BOM) with LF line endings.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutputFile, $sb.ToString(), $utf8NoBom)

Write-Host ("Wrote {0} ({1} error codes)" -f $OutputFile, $byName.Count)
