[CmdletBinding()]
param(
    [string] $InteropFile  = (Join-Path $PSScriptRoot '..\Strand7Sharp\Interop\St7API.cs'),
    [string] $OutputFile   = (Join-Path $PSScriptRoot '..\Strand7Sharp\Generated\St7Native.g.cs')
)
$ErrorActionPreference = 'Stop'
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputFile) | Out-Null
$src = Get-Content -LiteralPath $InteropFile -Raw
$rx = [regex]'public\s+static\s+extern\s+int\s+(St7[A-Za-z0-9_]+)\s*\(([^)]*)\)\s*;'
$kw = @{}
foreach ($k in @('abstract','as','base','bool','break','byte','case','catch','char','checked',
    'class','const','continue','decimal','default','delegate','do','double','else','enum',
    'event','explicit','extern','false','finally','fixed','float','for','foreach','goto',
    'if','implicit','in','int','interface','internal','is','lock','long','namespace',
    'new','null','object','operator','out','override','params','private','protected','public',
    'readonly','ref','return','sbyte','sealed','short','sizeof','stackalloc','static','string',
    'struct','switch','this','throw','true','try','typeof','uint','ulong','unchecked',
    'unsafe','ushort','using','virtual','void','volatile','while')) { $kw[$k] = $true }
function ToCamel([string] $s) {
    if (-not $s) { return $s }
    $r = $s.Substring(0, 1).ToLowerInvariant() + $s.Substring(1)
    if ($script:kw.ContainsKey($r)) { return "@$r" }
    return $r
}
function Parse-ParamList([string] $list) {
    if ([string]::IsNullOrWhiteSpace($list)) { return @() }
    $items = $list -split '\s*,\s*' | Where-Object { $_ }
    $params = New-Object System.Collections.Generic.List[object]
    foreach ($p in $items) {
        $t = $p.Trim()
        $isRef = $false
        if ($t -match '^ref\s+(.+)$') { $isRef = $true; $t = $Matches[1].Trim() }
        $sp = $t.LastIndexOf(' ')
        if ($sp -lt 0) { $sp = $t.LastIndexOf("`t") }
        $type = $t.Substring(0, $sp).Trim()
        $name = $t.Substring($sp + 1).Trim()
        $params.Add([pscustomobject]@{ IsRef = $isRef; Type = $type; Name = $name }) | Out-Null
    }
    return ,$params
}
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('//     This file was generated by tools/Generate-Wrapper.ps1 from St7API.cs.')
[void]$sb.AppendLine('//     DO NOT EDIT BY HAND. Re-run the generator to refresh.')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine('#nullable enable')
[void]$sb.AppendLine('using System;')
[void]$sb.AppendLine('using System.Text;')
[void]$sb.AppendLine('using St7API;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace Strand7Sharp;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('/// <summary>')
[void]$sb.AppendLine('/// Managed-friendly wrapper around every St7API.dll P/Invoke. Every method')
[void]$sb.AppendLine('/// throws <see cref="St7Exception"/> on a non-zero error code. Output')
[void]$sb.AppendLine('/// parameters (ref / StringBuilder buffers) become method return values.')
[void]$sb.AppendLine('/// Method names preserve the St7 prefix so each maps 1:1 to its docs/api page.')
[void]$sb.AppendLine('/// </summary>')
[void]$sb.AppendLine('public static class St7Native')
[void]$sb.AppendLine('{')
$count = 0
foreach ($m in $rx.Matches($src)) {
    $name   = $m.Groups[1].Value
    $params = Parse-ParamList $m.Groups[2].Value
    $inputs   = New-Object System.Collections.Generic.List[string]
    $callArgs = New-Object System.Collections.Generic.List[string]
    $locals   = New-Object System.Collections.Generic.List[string]
    $outputs  = New-Object System.Collections.Generic.List[object]
    $skipNext = $false
    for ($i = 0; $i -lt $params.Count; $i++) {
        if ($skipNext) { $skipNext = $false; continue }
        $p = $params[$i]
        $cName = ToCamel $p.Name
        # strip @ for local-name decoration
        $bare = $cName.TrimStart('@')
        if ($p.IsRef) {
            $local = "__$bare"
            $locals.Add("$($p.Type) $local = default;") | Out-Null
            $callArgs.Add("ref $local") | Out-Null
            $outputs.Add([pscustomobject]@{ Name = $p.Name; Type = $p.Type; Local = $local }) | Out-Null
            continue
        }
        if ($p.Type -eq 'StringBuilder' -and $i + 1 -lt $params.Count) {
            $nextP = $params[$i + 1]
            if (-not $nextP.IsRef -and $nextP.Type -eq 'int' -and
                ($nextP.Name -match 'Max(String)?Len|MaxLen|BufferLen|StrLen|Length')) {
                $local = "__$bare"
                $locals.Add("var $local = new StringBuilder(St7.kMaxStrLen);") | Out-Null
                $callArgs.Add($local) | Out-Null
                $callArgs.Add('St7.kMaxStrLen') | Out-Null
                $outputs.Add([pscustomobject]@{ Name = $p.Name; Type = 'string'; Local = "$local.ToString()" }) | Out-Null
                $skipNext = $true
                continue
            }
        }
        $inputs.Add("$($p.Type) $cName") | Out-Null
        $callArgs.Add($cName) | Out-Null
    }
    $returnType = 'void'
    $returnExpr = $null
    if ($outputs.Count -eq 1) {
        $returnType = $outputs[0].Type
        $returnExpr = $outputs[0].Local
    }
    elseif ($outputs.Count -gt 1) {
        $tupleTypes = ($outputs | ForEach-Object { "$($_.Type) $($_.Name)" }) -join ', '
        $returnType = "($tupleTypes)"
        $tupleVals  = ($outputs | ForEach-Object { $_.Local }) -join ', '
        $returnExpr = "($tupleVals)"
    }
    $paramSig = $inputs -join ', '
    $callSig  = $callArgs -join ', '
    [void]$sb.AppendLine("    /// <inheritdoc cref=`"St7API.St7.$name`"/>")
    [void]$sb.AppendLine("    public static $returnType $name($paramSig)")
    [void]$sb.AppendLine('    {')
    foreach ($l in $locals) { [void]$sb.AppendLine("        $l") }
    [void]$sb.AppendLine("        St7Check.Check(St7.$name($callSig), `"$name`");")
    if ($returnExpr) { [void]$sb.AppendLine("        return $returnExpr;") }
    [void]$sb.AppendLine('    }')
    [void]$sb.AppendLine()
    $count++
}
[void]$sb.AppendLine('}')
[System.IO.File]::WriteAllText($OutputFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated $count wrappers -> $OutputFile" -ForegroundColor Green

